import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import ReduxProviders from "@/redux/ReduxProviders";
import { Toaster } from "@/components/ui/sonner";
import StoreLanguageProvider from "@/i18n/store-language-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" data-lt-installed="true">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProviders>
          <StoreLanguageProvider>
            <Toaster />
            {children}
          </StoreLanguageProvider>
        </ReduxProviders>
      </body>
    </html>
  );
}
